2 papers till now ;)
nkss-dev/atlas pull request #28
Opened 2023-11-06 17:57 UTC by ProtonStar12

2023-11-06 18:11 UTC, GetPsyched commented
Another name change will be required haha. It should be `eepc202-ms2...`, you've written `ms1` in the file name.

2023-11-06 18:37 UTC, GetPsyched commented
Also, could you send the syllabi which has these subjects? I can't find them anywhere.

2023-11-07 17:04 UTC, GetPsyched requested changes

2023-11-07 17:04 UTC, GetPsyched commented on question-papers/eepc203-ms1-2023-sep.nix
> +      }]
Marks are missing.

2023-11-08 06:30 UTC, ProtonStar12 commented on question-papers/eepc203-ms1-2023-sep.nix
> +      }]
done

2023-11-08 09:51 UTC, GetPsyched approved these changes
LGTM

2023-11-08 09:52 UTC, merged