Pull Request for GDSC task by Vaibhav
nkss-dev/atlas pull request #32
Opened 2023-11-11 18:17 UTC by IAlgorithmia

I have added a new course in the "courses" folder, and also a question paper of Discrete Mathematics in the "question-paper" folder.

2023-11-13 18:16 UTC, GetPsyched requested changes

2023-11-22 05:12 UTC, GetPsyched commented
@IAlgorithmia you there?

2023-11-22 05:49 UTC, IAlgorithmia commented
A very good morning sir

I'd like to apologize for my lack of response sir, the reason is that the
last 7 days were packed with tons of practical and vivas, all of which
required heavy preparation.

I will make all the specified changes and improvements, and create a second
pull request.

Regards

On Wed, Nov 22, 2023 at 10:42 AM Priyanshu Tripathi <
***@***.***> wrote:

> @IAlgorithmia <https://github.com/IAlgorithmia> you there?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nkss-dev/atlas/pull/32#issuecomment-1822126016>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJWM7GJVYEONXJVDIYNF4RLYFWCVBAVCNFSM6AAAAAA7HNLKYWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRSGEZDMMBRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-22 05:57 UTC, GetPsyched commented
No worries, take your time.

2023-11-23 08:45 UTC, closed without merging